### ISSUE TITLE
Add ability to specify appendix for executable jar

### ISSUE THREAD

**Issue by jtnelson** [stigkj/gradle-executable-jar-plugin#16]
Would be nice to specify the appendix to something other than "execjar"

**Comment by stigkj** [comment]
Do you think it also would be nice to replace the normally created jar? That is, only one jar is created, and that is the executable jar?

**Comment by jtnelson** [comment]
Yes! I can't think of any cases when having a non-executable lib jar
alongside the executable app jar makes sense.

On Thursday, January 16, 2014, Stig Kleppe-Jørgensen <
notifications@github.com> wrote:

> Do you think it also would be nice to replace the normally created jar?
> That is, only one jar is created, and that is the executable jar?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/stigkj/gradle-executable-jar-plugin/issues/16#issuecomment-32569446
> .

## 

Sent from my iPhone

**Comment by stigkj** [comment]
I have decided to abandon the project; look at [gradle-capsule-plugin](https://github.com/danthegoodman/gradle-capsule-plugin) for an alternative
