### ISSUE TITLE
No such property: mainClass for class: org.gradle.api.internal.project.DefaultProject_Decorated

### ISSUE THREAD

**Issue by hellobigbean** [stigkj/gradle-executable-jar-plugin#18]
According to Readme, After build , why there is "No such property: mainClass for class: org.gradle.api.internal.project.DefaultProject_Decorated"    ?

**Comment by stigkj** [comment]
hmm...I have not upgraded the plugin to work with Gradle after they released v2.0. I will try to do this soon.

**Comment by stigkj** [comment]
I've decided to abandon the project as there are better alternatives out there, for example [gradle-capsule-plugin](https://github.com/danthegoodman/gradle-capsule-plugin).
