### ISSUE TITLE
Build failed with java.lang.NoClassDefFoundError: org.gradle.api.internal.artifacts.repositories.CommonsHttpClientResolver

### ISSUE THREAD

**Issue by stigkj** [stigkj/gradle-executable-jar-plugin#9]
It seems this class is replaced with an IvyResolver in 1.0-milestone-7

**Comment by harschware** [comment]
+1 vote for a fix

**Comment by harschware** [comment]
The NoClassDefFoundError only comes up if you run gradle --stacktrace.  Without it you would see an error similar to:

C:\gtest>gradle tasks
:tasks

---

## All tasks runnable from root project

Default tasks: clean, build

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':tasks'.
  Cause: Could not determine the dependencies of task ':executable-jar'.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug
  option to get more log output.

BUILD FAILED

Total time: 3.106 secs

> Building
